backend:
  name: github
  repo: manavnagpal/manavnagpal     # ‚Üê your GitHub repo name
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    format: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Project Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "NEW Badge", name: "isNew", widget: "boolean", default: false }
